"""create_pressure_records_table

Revision ID: 24f92b040717
Revises: 20260215_0009
Create Date: 2026-02-17 00:57:55.036110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24f92b040717'
down_revision: Union[str, None] = '20260215_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pressure_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=False),
    sa.Column('sys_rate', sa.Integer(), nullable=False),
    sa.Column('dia_rate', sa.Integer(), nullable=False),
    sa.Column('wave_a', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('wave_b', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'measured_at', name='uq_pressure_records_device_measured_at')
    )
    op.create_index('ix_pressure_records_device_id', 'pressure_records', ['device_id'], unique=False)
    op.create_index('ix_pressure_records_measured_at', 'pressure_records', ['measured_at'], unique=False)
    op.create_index('ix_pressure_records_patient_id', 'pressure_records', ['patient_id'], unique=False)
    op.drop_index(op.f('ix_dpa_doctor_id'), table_name='doctor_patient_assignments')
    op.drop_index(op.f('ix_dpa_patient_id'), table_name='doctor_patient_assignments')
    op.create_index(op.f('ix_doctor_patient_assignments_doctor_id'), 'doctor_patient_assignments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_assignments_patient_id'), 'doctor_patient_assignments', ['patient_id'], unique=False)
    op.drop_constraint(op.f('ip_bans_ip_address_key'), 'ip_bans', type_='unique')
    op.drop_index(op.f('ix_ip_bans_ip_address'), table_name='ip_bans')
    op.create_index(op.f('ix_ip_bans_ip_address'), 'ip_bans', ['ip_address'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_ip_bans_ip_address'), table_name='ip_bans')
    op.create_index(op.f('ix_ip_bans_ip_address'), 'ip_bans', ['ip_address'], unique=False)
    op.create_unique_constraint(op.f('ip_bans_ip_address_key'), 'ip_bans', ['ip_address'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_doctor_patient_assignments_patient_id'), table_name='doctor_patient_assignments')
    op.drop_index(op.f('ix_doctor_patient_assignments_doctor_id'), table_name='doctor_patient_assignments')
    op.create_index(op.f('ix_dpa_patient_id'), 'doctor_patient_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_dpa_doctor_id'), 'doctor_patient_assignments', ['doctor_id'], unique=False)
    op.drop_index('ix_pressure_records_patient_id', table_name='pressure_records')
    op.drop_index('ix_pressure_records_measured_at', table_name='pressure_records')
    op.drop_index('ix_pressure_records_device_id', table_name='pressure_records')
    op.drop_table('pressure_records')
    # ### end Alembic commands ###
