"""add_details_to_login_attempt

Revision ID: 9ecb37e7bca8
Revises: f3c0eadc46a0
Create Date: 2026-02-17 16:10:38.023999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecb37e7bca8'
down_revision: Union[str, None] = 'f3c0eadc46a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_attempts', sa.Column('details', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_attempts', 'details')
    # ### end Alembic commands ###
