"""create_device_error_logs_table

Revision ID: f3c0eadc46a0
Revises: 24f92b040717
Create Date: 2026-02-17 03:23:52.140033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c0eadc46a0'
down_revision: Union[str, None] = '24f92b040717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_error_logs_device_id'), 'device_error_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_error_logs_id'), 'device_error_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_error_logs_id'), table_name='device_error_logs')
    op.drop_index(op.f('ix_device_error_logs_device_id'), table_name='device_error_logs')
    op.drop_table('device_error_logs')
    # ### end Alembic commands ###
